### ISSUE TITLE
Not working?  greyed out sites list?

### ISSUE THREAD

**Issue by alphex** [derimagia/pantheon-bitbar#1]
Thanks for looking in to this.

![image](https://cloud.githubusercontent.com/assets/597641/13433227/ed21e4e2-df9e-11e5-8ee0-8dc856d16480.png)

I altered passthrough_return() to print out the site list ...
![image](https://cloud.githubusercontent.com/assets/597641/13433271/18ed8018-df9f-11e5-90e5-5c1c376ed797.png)

You can see its still showing the Terminus auth error.

The first image shows that the menubar 'works' ?   but everythigns greyed out.

Thoughts?
Thanks!

**Comment by derimagia** [comment]
What version of terminus are you running? It looks like the lists you got back are not formatted in json like they should be. If you type "terminus sites list --format=json" do you get your results back in json?

If this isn't the case I think updating to the latest version will fix it. (And i'll update the readme to point this out). I also added a "Debug mod" variable to print this stuff out in the latest verison.

If you're curious to why it's greyed out, it's just printing out the debug message you have. Bitbar is pretty flexible in the fact that it reads any output and converts it into a menu.

**Comment by alphex** [comment]
==> Pouring terminus-0.10.5.el_capitan.bottle.tar.gz
Just ran brew upgrade terminus.
brought me to .10.5 el capitain...

and I still get the "Could not get site list. Did you auth using Terminus?"
error.

"terminus sites list --format=json"  gives me --> (screen shot)  (which
doesn't look like JSON...)
http://z.alphex.io/2016-03-01_12-06-59.jpg

Now I'm confused too :)

Thank you.

ᐧ

**Comment by derimagia** [comment]
Just to confirm can you run 'terminus cli version'?

**Comment by alphex** [comment]
Terminus 0.4-beta

That gotta be out of date...

will address.
ᐧ

**Comment by derimagia** [comment]
Let me know if it doesn't fix it. Brew may not be overwriting the terminus file for some reason. Download the latest copy of the plugin when you fix it because I fixed an issue with drush.
