### ISSUE TITLE
Could not get site list. Did you auth using Terminus?

### ISSUE THREAD

**Issue by pi-ron** [derimagia/pantheon-bitbar#2]
Looks like a helpful tool!

Experiencing the same issue as Duran, see below.  I have authed & tried removing the --cached flag as you suggested.

> Dave.
> 
> I'm getting the "Did you auth in terminus" message.
> I did... :)   and when I run the script in terminal, I get the same message.
> 
> Help?  Thoughts?
> 
> Thanks!
> 
> ] duran goodyear

**Comment by derimagia** [comment]
I added a debug option in the latest build if you want to check that out and send me any responses. It's at the top of the script.

Run "terminus cli version" and make sure you're running a newer version. Essentially we need to make sure when you run "terminus sites list --format=json" it'll give you a JSON response.

Take a look at https://github.com/derimagia/pantheon-bitbar/issues/1 to see if that's your issue
